### ISSUE TITLE
Local debugging

### ISSUE THREAD

**Issue by xuzhu-591** [horizoncd/horizon#86]
# Intro
The main development of Horizon is concentrated on horizon-core and horizon-web. The fallowing method is proposed to facilitate our coding and debugging: 

# Requirements

* Hardware: 8 CPU, 16GB
* Language envrionment: 
  * [golang](https://go.dev/) (version >= 1.15)
  * [node.js](https://nodejs.org/en/) (version >= v16)

* IDE: vscode, goland, etc.
* [Nocalhost extension](https://nocalhost.dev/docs/quick-start/).

# Debug process

## Horizon-core

Horizon-core is a web server built with gin framework. Due to its complex interaction with other components, we could use nocalhost tool to connect to kind locally for debugging.

1. Download nocalhost extension

2. Open nocalhost's panel, click the "+" button, add the kubeconfig location, and select context and namespace.
![image](https://user-images.githubusercontent.com/62157058/225304306-fed151c2-ed4e-46d3-ad51-9612bf4fcfa3.png)

3. Start DevMode: select kind -> horizoncd -> horizon ->Deployments -> horizon-core. Start DevMode in the right-click menu.
![image](https://user-images.githubusercontent.com/62157058/225304382-7ef69102-c4c9-49ca-a0fe-c80ed1d84250.png)

4. Remote debugging: click Remote Debug in the right-click menu, and wait for the service to start.

5. Debug your code!

## Horizon-web

1. change proxy to forward requests to horizon-core deployed on your k8s.

   ```ts
   // config/proxy.ts
   export default {
     dev: {
       '/apis/': {
         // target: 'http://localhost:8080',
         target: 'http://horizon.h8r.site'
         changeOrigin: true,
         pathRewrite: { '^': '' },
       },
     },
   };
   ```

2. start the project and visit http://localhost:8000 for debugging.

   ```shell
   # prepare
   yarn
   # start
   yarn start
   ```

**Comment by xuzhu-591** [comment]
[TOC]

# Intro

Horizon项目主要的开发工作集中于**后端web服务器**和**前端web页面**，为方便开发者对感兴趣的需求进行开发，下面介绍一下如何在**本地**进行前后端开发以及联调。

# Requirements

* Hardware: 8 CPU, 16GB
* Language envrionment: 
  * [golang](https://go.dev/) (version >= 1.15)
  * [node.js](https://nodejs.org/en/) (version >= v16)

* IDE: vscode, goland, etc.
* [Nocalhost extension](https://nocalhost.dev/docs/quick-start/).

# Debug process

## Horizon-core

后端项目是一个使用 gin 搭建的 web 服务器，由于其与其他组件交互较为复杂，我们直接在本地借助 nocalhost 工具连接 kind 进行调试。

1. 下载 IDE 的 nocalhost 插件


2. 连接 kind 集群：打开 nocalhost 的面板，点击“+”加号，添加 kubeconfig 位置，然后选择 context 和 namespace。
![image](https://user-images.githubusercontent.com/62157058/225304306-fed151c2-ed4e-46d3-ad51-9612bf4fcfa3.png)

3. 进入开发模式 (DevMode): 侧边栏找到 kind -> horizoncd -> horizon ->Deployments -> horizon-core，右键菜单中启动开发模式 (Start DevMode)。
![image](https://user-images.githubusercontent.com/62157058/225304382-7ef69102-c4c9-49ca-a0fe-c80ed1d84250.png)


5. 远程调试：右键菜单点击远程调试 (Remote Debug)，等待服务启动，即可调试项目。

## Horizon-web

1. 修改前端 proxy，将前端请求转发到 kind 内的 horizon-core

   ```ts
   // config/proxy.ts
   export default {
     dev: {
       '/apis/': {
         // target: 'http://localhost:8080',
         target: 'http://horizon.h8r.site'
         changeOrigin: true,
         pathRewrite: { '^': '' },
       },
     },
   };
   ```

2. 启动项目，访问 http://localhost:8000 进行调试

   ```shell
   # prepare
   yarn
   # start
   yarn start
   ```

**Comment by xuzhu-591** [comment]
Override config file in path `.nocalhost/config.yaml` as follows: 
(This file will be committed later.)
```yaml
name: horizon-core
serviceType: deployment
containers:
  - name: core
    dev:
      gitUrl: ""
      image: horizoncd/go-dlv:v2.0.0
      sidecarImage: horizoncd/nocalhost-sidecar:syncthing
      # aliyun registry for domestic developer
#      image: registry.cn-hangzhou.aliyuncs.com/horizoncd/go-dlv:v2.0.0
#      sidecarImage: registry.cn-hangzhou.aliyuncs.com/horizoncd/nocalhost-sidecar:syncthing
      shell: ""
      workDir: "/home/appops"
      storageClass: ""
      persistentVolumeDirs: []
      command:
        run:
          - .nocalhost/run.sh
        debug:
          - .nocalhost/debug.sh
      debug:
        remoteDebugPort: 9009
      hotReload: false
      sync:
        type: "send"
        mode: "pattern"
        filePattern: []
        ignoreFilePattern:
          - "./build"
          - "./db"
          - "./mock"
          - "./openapi"
      env: []
      portForward: []

```
